#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - python3
  - python3-pip
  - python3-venv


runcmd:
  # tofu install instructions from https://opentofu.org/docs/intro/install/deb/
  # Download the installer script:
  - curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
  # Alternatively: wget --secure-protocol=TLSv1_2 --https-only https://get.opentofu.org/install-opentofu.sh -O install-opentofu.sh
  # Give it execution permissions:
  - chmod +x install-opentofu.sh

  # Please inspect the downloaded script
  # Run the installer:
  - ./install-opentofu.sh --install-method deb
  # Remove the installer:
  - rm install-opentofu.sh	
